# ZOO_MY_ID表示ZK服务的 ID，它是1-255 之间的整数，必须在集群中唯一
# ZOO_SERVERS是ZK 集群的主机列表

version: '3.1'

services:
  zoo1:
    image: zookeeper:3.4.14
    restart: always
    hostname: zoo1
    container_name: zoo1
    # privileged: true
    ports:
      - 2181:2181
    # volumes: # 挂载数据卷
    #   - ./zoo1/data:/data
    #   - ./zoo1/datalog:/datalog      
    environment:
      TZ: Asia/Shanghai  
      ZOO_MY_ID: 1 # 节点ID
      ZOO_PORT: 2181 # zookeeper端口号
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    # networks:
    #   default:
    #     ipv4_address: 172.23.0.11      

  zoo2:
    image: zookeeper:3.4.14
    restart: always
    hostname: zoo2
    container_name: zoo2
    # privileged: true
    ports:
      - 2182:2181
    # volumes: # 挂载数据卷
    #   - ./zoo2/data:/data
    #   - ./zoo2/datalog:/datalog      
    environment:
      TZ: Asia/Shanghai         
      ZOO_MY_ID: 2
      ZOO_PORT: 2181      
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    # networks:
    #   default:
    #     ipv4_address: 172.23.0.12

  zoo3:
    image: zookeeper:3.4.14
    restart: always
    hostname: zoo3
    container_name: zoo3
    # privileged: true    
    ports:
      - 2183:2181
    # volumes: # 挂载数据卷
    #   - ./zoo3/data:/data
    #   - ./zoo3/datalog:/datalog       
    environment:
      TZ: Asia/Shanghai         
      ZOO_MY_ID: 3
      ZOO_PORT: 2181       
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    # networks:
    #   default:
    #     ipv4_address: 172.23.0.13      

networks:
    default:
      external:
        name: zoo_kafka      # 如果不想创建则注释